jeffijoe/awilix

- lib/createContainer.js
The current master branch fails to build on webpack2 due to the `options.require || require` statement on line 81.
I have wrapped `require` as a dynamic function so that it will build with webpack2.
In addition, I have created an issue on webpack's page for this, as I believe the blame ultimately rests on them. However, for the sake of compatibility, I've made this PR.
> Fix require statement for webpack2 compatibility

- index.d.ts
- tsconfig.json
I'm using stricter checks in my own project, and it fails to compile because of the missing return in one of the registerFunction declarations. I've added the stricter checks to the tsconfig.json so the test will fail if this happens again.
> Stricter tsconfig. Fixed implicit return in TS typings.

- lib/AwilixNotAFunctionError.js
- lib/registrations.js
- test/lib/isFunction.spec.js
- test/lib/registrations.spec.js
Fixes issue #20 
In asClass/asFunction if isFunction is false for the first parameter, we throw an AwilixNotAFunctionError with a message like : "The function asClass expected a class, undefined given.", "The function asFunction expected a function, object given."...
Updated test for asClass, asFunction and isFunction
> Guard assertions

- CHANGELOG.md
- README.md
- index.d.ts
- lib/AwilixError.js
- lib/AwilixNotAFunctionError.js
- lib/AwilixResolutionError.js
- lib/createContainer.js
- package.json
- test/index.ts
- test/lib/createContainer.spec.js
- yarn.lock
This PR implements #26 and fixes some TS typings.
Also added some more meat to the README.
> Infer name from function/class (#26)

- index.d.ts
The current TypeScript definition for `container.loadModules` has a return value of ModuleDescriptor[], This is correct for lib/loadModules, but container.loadModules returns container instead.
This PR corrects that minor detail.
> [TypeScript] container.loadModules returns container

- .travis.yml
This will speed up Travis builds by caching `node_modules`.
> chore(travis): use cache directory to speed up CI build

- lib/createContainer.js
- test/lib/createContainer.spec.js
In this PR:
* cradle[Symbol.iterator] returns a generator that iterates registration names
* add a test for cradle[Symbol.iterator] (by using Array.from)
* add a test for using util.inspect on the cradle
* modify test for spreading cradle into an array
This can help in cases where it's needed to look on the registrations in a cradle without resolving them, when there is no access to the `container` that it came from.
> Support iterating registrations using cradle

- README.md
- package.json
- src/__tests__/__snapshots__/function-tokenizer.test.ts.snap
- src/__tests__/container.test.ts
- src/__tests__/function-tokenizer.test.ts
- src/__tests__/param-parser.test.ts
- src/container.ts
- src/function-tokenizer.ts
- src/param-parser.ts
- src/resolvers.ts
- src/utils.ts
- yarn.lock
This PR adds support for default parameters. When a parameter has no registration in the container, if it has a default value then Awilix will return `undefined`, causing the JS runtime to use the default value.
Closes #46
> Default parameter value support

- README.md
I saw this for a while and looked into the sources and it's in fact a mistake.
> docs: fixed wrong args `container.loadModules()`

- .travis.yml
- README.md
- package.json
- rollup.config.js
- src/__tests__/rollup.test.ts
- src/container.ts
- src/errors.ts
- yarn.lock
This PR includes Rollup builds of Awilix so it can be used in the browser, as well as ES-modules friendly files for maximum tree-shaking benefits. 🌲 
The browser versions **do not support `loadModules` and `listModules` due to depending on `glob`**. This is stripped out in the build by Rollup.
> Add Rollup builds to support Browser environments

- src/container.ts
Suggestion for resolving typing issues with `container.cradle` (#83)
> [#83] Changed cradle typing into  to enable casting

- README.md
After the going through the discussion at [Cyclic dependencies detected](https://github.com/jeffijoe/awilix/issues/94), I believe its good to update the readme file of this package. So that its easy to find that we can have `resolverOptions` per module as well in a single `container.loadModules`
From
```
container.loadModules([
// Globs
'services/**/*.js',
'repositories/**/*.js'
], {
// We want to register `UserService` as `userService` -
// by default loaded modules are registered with the
// name of the file (minus the extension)
formatName: 'camelCase',
// Apply resolver options to all modules.
resolverOptions: {
// We can give these auto-loaded modules
// the deal of a lifetime! (see what I did there?)
// By default it's `TRANSIENT`.
lifetime: Lifetime.SINGLETON,
// We can tell Awilix …
```
> updated readme file to include resolverOptions for single module in container.loadModules

- CHANGELOG.md
- README.md
- package.json
- src/__tests__/container.test.ts
- src/container.ts
- yarn.lock
* Scoped containers no longer
use the parent's cache for `Lifetime.SCOPED` registrations
* Change the `"react-native"` module path to
use `awilix.browser.js` (#104)
* Update packages
BREAKING CHANGE — closes #92, closes #104
> fix(scope): only use scope-local cache

- .gitignore
- src/__tests__/container.test.ts
- src/container.ts
This handles the case related to #109 to allow for friendly usage in async contexts.
@jeffijoe — I've maintained 100% coverage. Are there any specific tests you were looking for me to add?
> Makes promise-friendly handling interactions with "then" property

- README.md
If you skip this step, you'll get an error during testing:
```
Cannot find module '../../lib/awilix' from 'rollup.test.ts'
```
> Adding note to run a build

- README.md
- src/__tests__/load-modules.test.ts
- src/load-modules.ts
Module default exports are discouraged in e.g. [`tslint`](https://palantir.github.io/tslint/rules/no-default-export/); the `no-default-export` setting is set to true when using out-of-the-box settings for the quite popular [`gts`](https://www.npmjs.com/package/gts) styles.
This proposed PR allows for a non-default export to be loaded if it contains a static property with the `RESOLVER` key, even if that property is just an empty object. The dropped default export requirement would allow for better compliance with these `tslint` best practices.
Because the default export is tried first and non-default exports must have the `RESOLVER` key, the change should be fully backward-compatible.
Tests have been amended to cover this case. Suggestions are welcome!
> feat: allow autoloading of non-default exports

- CHANGELOG.md
- README.md
- examples/babel/.babelrc
- src/__tests__/inheritance.test.js
- src/resolvers.ts
This PR adds support for extracting dependencies from base classes, both using ES6 classes and old-school prototype approach.
Closes #107
> feat(classes): support base classes/prototypes

- src/__tests__/container.test.ts
- src/container.ts
There are scenarios where it is required to know if a registration already exists or it would be useful to know if a registration already exists to avoid overwrites or other modifications.
> feat(container): add has method to check for registration existence

- examples/simple/index.js
cool project!
i was trying to run the example from the `awilix/` dir and kept getting mysterious resolution errors:
```
/.../awilix/lib/container.js:335
throw err;
^
Error: Could not resolve 'classicalService'.
Resolution path: classicalService
```
> fix(examples/simple): don't rely on relative paths

- src/__tests__/container.test.ts
- src/container.ts
Winston, sentry, and many more libraries, which call internally `JSON.stringify` or some other (custom) function for JSON serialization, cause a memory leak when passed a container cradle.
I especially had the case together with Sequelize and winston json formatter. For some reason, sometimes (mostly in case of errors) it tried to log the whole container cradle. This took forever and resulted in a silent app crash which was not immediately traced back to the problems roots.
This PR simply checks if the container cradle was called via `JSON.stringify` by checking for `toJSON` and returns a simple string.
Following github issues are connected to this:
https://github.com/coopernurse/node-pool/issues/275
https://github.com/sequelize/sequelize/issues/10443
Thanks!
> JSON.stringify() container cradle results in memory leak because of cyclic references

- src/container.ts
> fix(container): createScope return defaults to original container

- src/__tests__/container.test.ts
- src/errors.ts
I use symbols heavily in resolution so they may exist on multiple levels. I found the AwilixResolutionError was throwing another error: "TypeError: Cannot convert a Symbol value to a string". The symbol "names" in the resolution stack were failing on the array join. I added a test to cover this scenario.
Code coverage: 100%
Linting Passes
Please let me know if there is anything else you would like me to do.
> Fixes AwilixResolutionError throwing TypeError if resolution stack contains symbols.

- README.md
- package-lock.json
- package.json
- rollup.config.js
- src/__tests__/container.test.ts
- src/__tests__/load-modules.test.ts
- src/container.ts
- src/list-modules.ts
- src/load-module-native.d.ts
- src/load-module-native.js
- src/load-modules.ts
Fixes #210 
Sadly it's not possible to test the native specific parts since jest doesn't do mocks of the native `import()` function. However since I broke all the logic out to separate functions the real difference between loading modules using ES modules and CJS is negligible.
> Added support for native Node ES6 modules

- package-lock.json
- package.json
Noticed this issue when my lambda dependencies started blowing up. Hoping for a quick patch release 🤞🏻  Thanks!
> Move rollup-plugin-copy to devDependencies

- src/container.ts
Would allow calls like this
```
interface CradleType {
readonly someServiceKey: SomeService;
}
const container = createContainer<ContainerType>();
container.register({
someServiceKey: asFunction(createSomeService)
});
// still allows
container.register('someValue', asValue('stringValue'));
// this is the benefit
const someService = container.resolve('someServiceKey');
// above will be typed as 'SomeService' (because of new added declaration)
// also will help with code completing of used string
// dont need:
// const someService = container.resolve<SomeService>('someServiceKey'); // no type checking of used string (whether it matches a key in CradleType)
// or
// const someService = container.resolve('someServiceKey') as SomeService; // explicit cast
// also still allowed (will match the …
```
> Improve resolve typing

- src/list-modules.ts
Hi Jeff, one small update on this one.
In this file there are 2 checks to verify if it is an array. First uses `Array.isArray` and the other `instanceof` 
Looks like the Array.isArray is preferred over instanceof:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/isArray#instanceof_vs_isarray
> Array.isArray is preferred over instanceof

- src/function-tokenizer.ts
- src/injection-mode.ts
- src/param-parser.ts
- src/utils.ts
- Adding a few missing return boolean types
- lower case boolean type based on this "[It is recommended to use the primitive type boolean](https://www.tutorialsteacher.com/typescript/typescript-boolean)"
- Adding an empty line on **injection-mode.ts** just to keep consistency with **lifetime.ts**
> Adding a few missing boolean return types.

- src/__tests__/awilix.test.ts
- src/__tests__/container.test.ts
- src/__tests__/integration.test.ts
- src/__tests__/list-modules.test.ts
- src/__tests__/local-injections.test.ts
- src/__tests__/param-parser.test.ts
- src/__tests__/utils.test.ts
Hi,
while reading the tests I saw a few places declaring functions with `function ()` and other with `arrow functions`.
I imagine arrow functions are preferred so, to keep it consistent, updating all to use arrow functions.
Let me know if thats ok, 
Thanks!
> Update tests to use arrow functions when possible.

- src/__tests__/container.test.ts
Removing the parameter `cradle` from the `second` registered function since it's not used.
> Remove unused parameter from test.

- src/__tests__/load-modules.test.ts
- removes unnecessary `async` 
I understand that the test `'registers loaded modules async when using native modules'` is testing the bellow line to be `async` so the one removed isn't necessary. Please, correct me if I'm wrong.
`    const result = await loadModules(deps, 'anything', { esModules: true })
`
All tests passing.
Thanks.
> Updates a few function declarations to arrow functions and more.

- src/container.ts
Fixing 2 linter warning on `container.ts`.
JSDoc types may be moved to TypeScript types.ts(80004)
This assertion is unnecessary since it does not change the type of the expression. (no-unnecessary-type-assertion)tslint(1)
All tests passing.
> chore: Fix linter warnings.

- src/__tests__/load-modules.test.ts
Removing un used `desc` from load.modules.test.
> chore(tests): remove unused desc from load-modules-test

- README.md
> docs: rename .has to .hasRegistration

- CHANGELOG.md
- package-lock.json
- package.json
- src/__tests__/list-modules.test.ts
- src/list-modules.ts
**Problem**: `fast-glob` only works with `/`.
**Solution**: replace all `\` with `/` in the glob pattern before passing to `fast-glob`.
Closes #291
> Fix fast-glob usage on Windows

- README.md
We have implemented additional wrapper on top of Awilix in Lokalise, it may be useful to other users of the awilix.
> docs: Add reference to awilix-manager

- src/__tests__/resolvers.test.ts
- src/resolvers.ts
Allow `aliasTo` to handle Symbol.
> Match parameter types of `aliasTo` from `container.resolve`

- CHANGELOG.md
- README.md
- examples/babel/.babelrc
- examples/babel/src/index.js
- examples/koa/index.js
- examples/simple/index.js
- examples/typescript/src/index.ts
- examples/typescript/tsconfig.json
- package-lock.json
- package.json
- src/__tests__/container.test.ts
- src/__tests__/lifetime.test.ts
- src/awilix.ts
- src/container.ts
- src/errors.ts
- src/lifetime.ts
- src/load-modules.ts
- src/resolvers.ts
- src/types.ts
Adds new container option `errorOnShorterLivedDependencies` which enables detection and errors on cases where a longer-lived module resolves a shorter-lived dependency, which is then preserved inside the longer-lived module even after its own lifetime and cached resolution expires.
Fixes #348
NOTE: this changes the interface of `ResolutionStack` which was technically exported but should never be needed by client code. Does this constitute a breaking change for versioning purposes?
> Add option to detect and error on dependency lifetime mismatch

- .eslintrc.cjs
- CHANGELOG.md
- package-lock.json
- package.json
- rollup.config.mjs
- src/container.ts
- src/load-modules.ts
The updated `awilix.ts` from the prior PR changed how `list-modules` was exported which needed to be accounted for in the `rollup` config.
Also updated some packages.
> Update packages, fix coverage and browser build

- README.md
package has been published: https://www.npmjs.com/package/awilix-vite
Closes #363
> Add awilix-vite in ecosystem section

- package.json
Reverting #369 because it broke consumers.
> fix(package): undo all exports changes as it breaks downstream adapters

- rollup.config.mjs
This PR fixes the browser build. I had added `type` prefixes to the `list-modules` export but forgot to update the `replace` section in the Rollup config.
> Properly strip Node-specific stuff from browser build

- README.md
- package.json
- rollup.config.mjs
- src/__tests__/rollup.test.ts
> Rename `awilix.browser.js` to `awilix.browser.mjs` + more `exports` conditionals
