- .gitignore
- index.d.ts
- package.json
- test/index.ts
- tsconfig.json
* Added index.d.ts TypeScript definitions.
* Created test/index.ts to test the TypeScript definitions.
* Test is compiled to /dist.
* Added ignore or root /dist directory to .gitignore.
* You can execute the test by swapping out the definitions with the real thing.
* Created /tsconfig.json for compiling TypeScript definition file test.
* A successful compilation == passed test.
* Added dependencies for mocha, mocha-typescript and DefinitelyTyped definitions for chai and node.
Resolves #14
> TypeScript definitions

- lib/loadModules.js
Hi, I need more advance functionality for register my object with some namespace.
Can you review my code and approve if all is alright. Thanks.
Example my formatter function
```js
formatName: (name, namespace) => {
return name + namespace.split('/').splice(2).reverse().map(
part => part.charAt(0).toUpperCase() + part.slice(1)
).join()
}
```
my application structure: src/domain/reporitory/account.js
I want register my class as accountRepository. And I have a big structure for that with many classes. 
As I think it's implement [DRY principle](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself)
PS: awesome library, thanks for your job.
> add relative path to name formatter

- CHANGELOG.md
- lib/parseParameterList.js
- lib/registrations.js
- package.json
- test/lib/parseParameterList.spec.js
- test/lib/registrations.spec.js
- yarn.lock
This PR substitutes the regex used to extract parameter info with a crude token-based parser with basic support for default parameter values.
Closes #30
> Fix issue 30

- CHANGELOG.md
- README.md
- index.d.ts
- lib/isClass.js
- lib/loadModules.js
- lib/parseParameterList.js
- lib/tokenizeFunction.js
- package.json
- test/index.ts
- test/lib/isClass.spec.js
- test/lib/loadModules.spec.js
This PR implements a custom `isClass` function that uses a commonly accepted convention for denoting newable functions using a capital first letter. This closes #28.
> Implement fix and feature in #28

- package.json
- yarn.lock
Updates packages to the latest versions.
> chore(package): update packages

- CHANGELOG.md
- README.md
- index.d.ts
- lib/AwilixNotAFunctionError.js
- lib/loadModules.js
- lib/registrations.js
- test/lib/createContainer.spec.js
- test/lib/loadModules.spec.js
This PR adds support for the proposed inline config feature proposed in #34.
> Inline config support

- CHANGELOG.md
- lib/loadModules.js
- lib/nameValueToObject.js
- package.json
- yarn.lock
Remove `is-plain-object` and `is-string`, use simple checks instead. Trying to keep the dependencies as thin as possible.
> Fix dependencies

- CHANGELOG.md
- README.md
- index.d.ts
- lib/AwilixTypeError.js
- lib/createContainer.js
- package.json
- test/index.ts
- test/lib/createContainer.spec.js
- yarn.lock
> Add `container.build()`

- README.md
- src/__tests__/awilix.test.ts
- src/__tests__/resolvers.test.ts
- src/resolvers.ts
This PR adds the `aliasTo` resolver proposed in #55
> feat: aliasTo resolver

- .gitignore
- CHANGELOG.md
- package.json
- rollup.config.js
- src/__tests__/load-modules.test.ts
- src/__tests__/resolvers.test.ts
- src/container.ts
- src/load-modules.ts
- yarn.lock
> fix(loadModules): spread inlineConfig on resolver opts

- README.md
Hello, `awilix` team,
Thank you for the awesome IoC tool for Nodejs.
A tiny fix while reading the documentation.
> Correct an important note phrase

- README.md
Fix API typo: .lifetime(...) -> .setLifetime(...)
> docs(typo): incorrect lifetime API

- src/utils.ts
Hello Jeff, really nice lib!
Please take a look at this small refactor on the uniq function on the utils file.
All the tests are passing, including the linters. 
Thank you.
> Refactor 'uniq' function to use a Set.

- src/container.ts
Hi,
I'm still reading the source code but I believe these variables are unused.
All tests are passing.
Thanks.
> Removing unused vars.

- src/__tests__/container.test.ts
Adding types to the expected injected property `repo` to be of the type `Repo`.
> Add type to injected repo object.

- src/__tests__/local-injections.test.ts
- src/__tests__/resolvers.test.ts
One more to favor arrow functions over regular function declaration on two tests.
> A few arrow functions clean ups.

- README.md
> docs: add inline resolver name precedence rule

- package-lock.json
- package.json
- rollup.config.js
- src/list-modules.ts
using `fast-glob` as glob library.
it is faster than `glob` and supports all of the same matching as minimatch.
Closes #283
> feat: use fast-glob instead of glob

- README.md
> Add blurb about Awilix' main selling point to the README

- CHANGELOG.md
- package.json
Closes https://github.com/jeffijoe/awilix/issues/368
> Add exports field in package.json
